# Site settings
name: Jiangg21
location: 北京
company: 北京荣大科技股份有限公司
position: Web前端开发工程师
github: https://github.com/
facebook: https://www.facebook.com/
wexin: Coder-wang0421
email: 2467511525@qq.com

baseurl: "/resume.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

